# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import datamanager_pb2 as datamanager__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in datamanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/datamanager.DataManager/Create',
                request_serializer=datamanager__pb2.ElectricInfo.SerializeToString,
                response_deserializer=datamanager__pb2.Response.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/datamanager.DataManager/Read',
                request_serializer=datamanager__pb2.ElectricID.SerializeToString,
                response_deserializer=datamanager__pb2.Response.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/datamanager.DataManager/Update',
                request_serializer=datamanager__pb2.ElectricInfo.SerializeToString,
                response_deserializer=datamanager__pb2.Response.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/datamanager.DataManager/Delete',
                request_serializer=datamanager__pb2.ElectricID.SerializeToString,
                response_deserializer=datamanager__pb2.Response.FromString,
                _registered_method=True)
        self.ReadAllInDateSpan = channel.unary_unary(
                '/datamanager.DataManager/ReadAllInDateSpan',
                request_serializer=datamanager__pb2.DateSpan.SerializeToString,
                response_deserializer=datamanager__pb2.Response.FromString,
                _registered_method=True)


class DataManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAllInDateSpan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=datamanager__pb2.ElectricInfo.FromString,
                    response_serializer=datamanager__pb2.Response.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=datamanager__pb2.ElectricID.FromString,
                    response_serializer=datamanager__pb2.Response.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=datamanager__pb2.ElectricInfo.FromString,
                    response_serializer=datamanager__pb2.Response.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=datamanager__pb2.ElectricID.FromString,
                    response_serializer=datamanager__pb2.Response.SerializeToString,
            ),
            'ReadAllInDateSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAllInDateSpan,
                    request_deserializer=datamanager__pb2.DateSpan.FromString,
                    response_serializer=datamanager__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datamanager.DataManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datamanager.DataManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datamanager.DataManager/Create',
            datamanager__pb2.ElectricInfo.SerializeToString,
            datamanager__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datamanager.DataManager/Read',
            datamanager__pb2.ElectricID.SerializeToString,
            datamanager__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datamanager.DataManager/Update',
            datamanager__pb2.ElectricInfo.SerializeToString,
            datamanager__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datamanager.DataManager/Delete',
            datamanager__pb2.ElectricID.SerializeToString,
            datamanager__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAllInDateSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datamanager.DataManager/ReadAllInDateSpan',
            datamanager__pb2.DateSpan.SerializeToString,
            datamanager__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
