# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datamanager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datamanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61tamanager.proto\x12\x0b\x64\x61tamanager\"\x18\n\nElectricID\x12\n\n\x02id\x18\x01 \x01(\x05\"\xe5\x01\n\x0c\x45lectricInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x1b\n\x13global_active_power\x18\x04 \x01(\x02\x12\x1d\n\x15global_reactive_power\x18\x05 \x01(\x02\x12\x0f\n\x07voltage\x18\x06 \x01(\x02\x12\x18\n\x10global_intensity\x18\x07 \x01(\x02\x12\x16\n\x0esub_metering_1\x18\x08 \x01(\x02\x12\x16\n\x0esub_metering_2\x18\t \x01(\x02\x12\x16\n\x0esub_metering_3\x18\n \x01(\x02\";\n\x10\x45lectricInfoList\x12\'\n\x04info\x18\x01 \x03(\x0b\x32\x19.datamanager.ElectricInfo\"0\n\x08\x44\x61teSpan\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\"X\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12+\n\x04list\x18\x03 \x01(\x0b\x32\x1d.datamanager.ElectricInfoList2\xba\x02\n\x0b\x44\x61taManager\x12:\n\x06\x43reate\x12\x19.datamanager.ElectricInfo\x1a\x15.datamanager.Response\x12\x36\n\x04Read\x12\x17.datamanager.ElectricID\x1a\x15.datamanager.Response\x12:\n\x06Update\x12\x19.datamanager.ElectricInfo\x1a\x15.datamanager.Response\x12\x38\n\x06\x44\x65lete\x12\x17.datamanager.ElectricID\x1a\x15.datamanager.Response\x12\x41\n\x11ReadAllInDateSpan\x12\x15.datamanager.DateSpan\x1a\x15.datamanager.ResponseB\x0e\xaa\x02\x0b\x44\x61taManagerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datamanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013DataManager'
  _globals['_ELECTRICID']._serialized_start=34
  _globals['_ELECTRICID']._serialized_end=58
  _globals['_ELECTRICINFO']._serialized_start=61
  _globals['_ELECTRICINFO']._serialized_end=290
  _globals['_ELECTRICINFOLIST']._serialized_start=292
  _globals['_ELECTRICINFOLIST']._serialized_end=351
  _globals['_DATESPAN']._serialized_start=353
  _globals['_DATESPAN']._serialized_end=401
  _globals['_RESPONSE']._serialized_start=403
  _globals['_RESPONSE']._serialized_end=491
  _globals['_DATAMANAGER']._serialized_start=494
  _globals['_DATAMANAGER']._serialized_end=808
# @@protoc_insertion_point(module_scope)
